### ISSUE TITLE
elm-format + autocomplete

### ISSUE THREAD

**Issue by MartinKavik** [pzavolinsky/elmx#14]
Hi, thank You for the super library!

I really want to use it, but I don't know how to solve incompatibility with other IDE extensions - I tried:

1. **Visual Studio Code** (*.elmx compilation with **[Gulp](https://github.com/pzavolinsky/elmx/tree/master/example)** and **[elmx extension](https://marketplace.visualstudio.com/items?itemName=realazy.elmx)** for syntax highlighting)
   - Is it possible to format code on save (with elm-format) and don't break autocomplete (and other functions) provided by **[elm extension](https://marketplace.visualstudio.com/items?itemName=sbrink.elm)**?

2. **Atom** (extensions: [elm-format](https://atom.io/packages/elm-format), [language-elm](https://atom.io/packages/language-elm), [language-elmx](https://atom.io/packages/language-elmx), [linter-elm-make](https://atom.io/packages/linter-elm-make))
   - *A)* Is it possible to format code on save?
   - *C)* I think it has some problems with **linter-ui-default** (viz [screenshot](http://prnt.sc/f60dvm)) (It will be better to create a new issue for this imho)
   - *B)* There is maybe another bug with linter - some red lines aren't associated with any lint errors

Thank you very much! I'll try to help as possible.
*Windows 10 - Atom 1.16.0 - VS Code 1.12.1*

**Comment by danneu** [comment]
Yeah, I also experience point C pretty excessively. If there's any sort of red underline indicating an error, hovering over it auto-opens my JS console and spits out hundreds of errors regarding linter-ui-default.

```
Uncaught TypeError: range.intersectsWith is not a function
    at /Users/danneu/.atom/packages/linter-ui-default/lib/helpers.js:84:53
    at Set.forEach (native)
    at filterMessagesByRangeOrPoint (/Users/danneu/.atom/packages/linter-ui-default/lib/helpers.js:81:12)
    at Editor.updateTooltip (/Users/danneu/.atom/packages/linter-ui-default/lib/editor/index.js:223:22)
    at /Users/danneu/.atom/packages/linter-ui-default/lib/editor/index.js:184:12
    at later (/Users/danneu/.atom/packages/linter/node_modules/sb-debounce/index.js:9:14)
```
